CREATE TABLE IF NOT EXISTS CUSTOMER (
	     ORDER_ID INTEGER AUTO_INCREMENT,
             CUSTOMER_CAR_MODEL VARCHAR (20) NOT NULL,
             CUSTOMER_BODY_COLOR VARCHAR (20),
	     CUSTOMER_ENGINE_CAPACITY INTEGER,
	     CUSTOMER_INTERIOR_MATERIAL VARCHAR (20),
	     CUSTOMER_INTERIOR_COLOR VARCHAR (20),
	     CUSTOMER_TIRE_SIZE INTEGER,
	     CUSTOMER_OPTIONAL_NO INTEGER,
	     ORDER_STATUS VARCHAR (20),
	     PRIMARY_KEY (ORDER_ID)
);
